extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: module
env:
  es6: true
rules:
  prettier/prettier: error
# conflicts with Node's relative import algorithm in ESM mode, see
# https://github.com/nodejs/node/issues/38484 and
# https://github.com/import-js/eslint-plugin-import/issues/2104
  import/extensions: off
  camelcase: off
  no-console: off
  no-empty:
    - error
    - allowEmptyCatch: true
  no-param-reassign:
    - error
    - props: false
  no-restricted-syntax: off
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_(ignored|unused)"
