extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: module
env:
  es6: true
rules:
  prettier/prettier: [error]
  camelcase: off
  no-console: off
  no-empty:
    - error
    - allowEmptyCatch: true
  no-restricted-syntax: off
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_(ignored|unused)"
